CREATE TABLE "DBA"."100_AUTHORS" (
	"author_id" NUMERIC(9,0) NOT NULL DEFAULT AUTOINCREMENT,
	"author_name" VARCHAR(255) NULL,
	PRIMARY KEY ( "author_id" ASC )
);

CREATE TABLE "DBA"."101_PUBLISHERS" (
	"publisher_id" NUMERIC(9,0) NOT NULL DEFAULT AUTOINCREMENT,
	"publisher_name" VARCHAR(255) NULL,
	PRIMARY KEY ( "publisher_id" ASC )
);

CREATE TABLE "DBA"."102_BOOKS" (
	"isbn" NUMERIC(9,0) NOT NULL DEFAULT AUTOINCREMENT,
	"title" VARCHAR(255) NULL,
	"no_of_pages" NUMERIC(9,0) NULL,
	"year_published" NUMERIC(4,0) NULL,
	"publisher_id" NUMERIC(9,0) NULL,
	PRIMARY KEY ( "isbn" ASC )
);

ALTER TABLE "DBA"."102_BOOKS" ADD CONSTRAINT "FK_102_101_PUBLISHERS" FOREIGN KEY ( "publisher_id" ASC ) REFERENCES "DBA"."101_PUBLISHERS" ( "publisher_id" );

CREATE TABLE "DBA"."103_BOOKS_AUTHORS" (
	"isbn" NUMERIC(9,0) NOT NULL,
	"author_id" NUMERIC(9,0) NOT NULL,
	PRIMARY KEY ( "isbn" ASC, "author_id" ASC )
);

ALTER TABLE "DBA"."103_BOOKS_AUTHORS" ADD CONSTRAINT "FK_103_100" NOT NULL FOREIGN KEY ( "author_id" ASC ) REFERENCES "DBA"."100_AUTHORS" ( "author_id" );
ALTER TABLE "DBA"."103_BOOKS_AUTHORS" ADD CONSTRAINT "FK_103_102" NOT NULL FOREIGN KEY ( "isbn" ASC ) REFERENCES "DBA"."102_BOOKS" ( "isbn" );

CREATE TABLE "DBA"."104_BOOKS_COPIES" (
	"copy_id" NUMERIC(9,0) NOT NULL DEFAULT AUTOINCREMENT,
	"isbn" NUMERIC(9,0) NOT NULL,
	PRIMARY KEY ( "copy_id" ASC )
);

ALTER TABLE "DBA"."104_BOOKS_COPIES" ADD CONSTRAINT "FK_104_102" NOT NULL FOREIGN KEY ( "isbn" ASC ) REFERENCES "DBA"."102_BOOKS" ( "isbn" );

CREATE TABLE "DBA"."105_USERS" (
	"user_id" NUMERIC(9,0) NOT NULL DEFAULT AUTOINCREMENT,
	"user_name" VARCHAR(255) NULL,
	"user_email" VARCHAR(255) NULL,
	"user_phone" VARCHAR(255) NULL,
	PRIMARY KEY ( "user_id" ASC )
);

CREATE TABLE "DBA"."106_LOANS" (
	"loan_id" NUMERIC(9,0) NOT NULL DEFAULT AUTOINCREMENT,
	"copy_id" NUMERIC(9,0) NOT NULL,
	"user_id" NUMERIC(9,0) NOT NULL,
	"due_date" TIMESTAMP NULL DEFAULT dateadd(dd, 90, current date),
	PRIMARY KEY ( "loan_id" ASC )
);

ALTER TABLE "DBA"."106_LOANS" ADD CONSTRAINT "106_104_COPIES" NOT NULL FOREIGN KEY ( "copy_id" ASC ) REFERENCES "DBA"."104_BOOKS_COPIES" ( "copy_id" );
ALTER TABLE "DBA"."106_LOANS" ADD CONSTRAINT "106_105_USERS" NOT NULL FOREIGN KEY ( "user_id" ASC ) REFERENCES "DBA"."105_USERS" ( "user_id" );

CREATE TABLE "DBA"."107_SUBJECTS" (
	"subject_id" NUMERIC(9,0) NOT NULL DEFAULT AUTOINCREMENT,
	"subject_name" VARCHAR(255) NULL,
	PRIMARY KEY ( "subject_id" ASC )
);

CREATE TABLE "DBA"."108_BOOKS_SUBJECTS" (
	"isbn" NUMERIC(9,0) NOT NULL,
	"subject_id" NUMERIC(9,0) NOT NULL,
	PRIMARY KEY ( "isbn" ASC, "subject_id" ASC )
);

ALTER TABLE "DBA"."108_BOOKS_SUBJECTS" ADD CONSTRAINT "108_102_BOOKS" NOT NULL FOREIGN KEY ( "isbn" ASC ) REFERENCES "DBA"."102_BOOKS" ( "isbn" );
ALTER TABLE "DBA"."108_BOOKS_SUBJECTS" ADD CONSTRAINT "108_107_SUBJECTS" NOT NULL FOREIGN KEY ( "subject_id" ASC ) REFERENCES "DBA"."107_SUBJECTS" ( "subject_id" );
















